import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// =============================================================================
// PayFast payment public summary — Step 8 PR F.
//
// Powers the buyer-facing /payment-success and /payment-cancelled pages.
// The pages are public (PayFast redirects the buyer back without any session),
// so this function is unauthenticated by design and must be defensive about
// what it exposes.
//
// Inputs (POST JSON):
//   { ref: "MIO-YYYYMMDDTHHMMSS-XXXXXX" }
//
// Output (200):
//   {
//     ref, pf_payment_id, package_id, package_name, amount, status,
//     customer_name, company_name, email, completed_at, created_at,
//   }
//
// Errors:
//   400 invalid_ref_format    — ref didn't match the m_payment_id regex.
//   404 not_found             — no Payment row for that ref.
//   405                       — non-POST method.
//   429 rate_limited          — IP exceeded 30 reqs / 5 min.
//
// Security:
//   - Whitelisted output. ipn_payload, signed_payload_hash, internal flags
//     and any column we add later are NEVER returned.
//   - ref must match the strict format generated by payfast-checkout-init
//     (`MIO-${stamp}-${randomToken(6)}`) before any DB call.
//   - Per-IP rate limit (sliding window, in-memory). On limit hit we drop a
//     SecurityEvent row for monitoring and return 429.
//   - The endpoint is read-only — no writes against Payment/Client.
// =============================================================================

const REF_REGEX     = /^MIO-\d{8}T\d{6}-[A-Z0-9]{6}$/;
const RATE_WINDOW_MS = 5 * 60 * 1000;
const RATE_MAX       = 30;

// In-memory rate-limit store. Best-effort: a multi-instance deployment will
// keep separate counters per instance, but this is still a meaningful abuse
// deterrent and the alternative (DB-backed) costs a write per request. If we
// later see distributed abuse we can promote this to Redis/Upstash.
const ipHits: Map<string, number[]> = new Map();

function clientIpFrom(req: Request): string {
  const xff = req.headers.get('x-forwarded-for');
  if (xff) return xff.split(',')[0].trim();
  return req.headers.get('x-real-ip')?.trim() ||
    req.headers.get('cf-connecting-ip')?.trim() ||
    'unknown';
}

// Returns true if the request should be rejected. Mutates `ipHits` to record
// the new attempt only when allowed.
function isRateLimited(ip: string): boolean {
  const now = Date.now();
  const cutoff = now - RATE_WINDOW_MS;
  const recent = (ipHits.get(ip) || []).filter((t) => t > cutoff);
  if (recent.length >= RATE_MAX) {
    ipHits.set(ip, recent);
    return true;
  }
  recent.push(now);
  ipHits.set(ip, recent);
  return false;
}

// Server-side mirror of package id → display name. Mirrors PAYFAST_PACKAGES
// in src/config/payfastPackages.js (Deno functions can't import from src/).
// Keep in sync. Same constraint as payfast-checkout-init and -send-receipt.
const PACKAGE_NAMES: Record<string, string> = {
  'ignite':                  'Ignite Setup',
  'accelerate':              'Accelerate Setup',
  'dominate':                'Dominate Setup',
  'street-pulse':            'Street Pulse Setup',
  'township-pulse':          'Township Pulse',
  'ai-chatbot':              'AI Chatbot Setup',
  'whatsapp-automation':     'WhatsApp Business Automation',
  'google-business-profile': 'Google Business Profile Setup',
  'sms-marketing':           'SMS Marketing Setup',
  'marketing-audit':         'Marketing Audit & Report',
  'competitor-analysis':     'Competitor Analysis Report',
  'crm-training':            'CRM Training & Setup',
  'ignite-test':             'Sandbox Test',
};

function unwrapOne(result: any): any {
  if (result == null) return null;
  if (Array.isArray(result)) return result[0] ?? null;
  if (typeof result === 'object') {
    if (result.id) return result;
    const inner = (result as any).data;
    if (Array.isArray(inner)) return inner[0] ?? null;
    if (inner && typeof inner === 'object' && inner.id) return inner;
  }
  return null;
}

async function logRateLimit(
  base44: any,
  ip: string,
  ref: string,
  userAgent: string,
): Promise<void> {
  // SecurityEvent.email is required by the schema, but rate-limit hits have
  // no associated user. Use a sentinel so the row is queryable by event_type
  // alone; real context goes into `details`.
  try {
    await base44.asServiceRole.entities.SecurityEvent.create({
      event_type: 'payment_summary_rate_limit',
      email:      'unknown@rate-limit',
      ip_address: ip,
      user_agent: userAgent.slice(0, 500),
      details:    JSON.stringify({ ref: ref.slice(0, 64), endpoint: 'payment-public-summary' }),
      created_at: new Date().toISOString(),
    });
  } catch (err) {
    // Don't let logging failure block the 429 response.
    console.error('[payment-public-summary] SecurityEvent.create failed:', err);
  }
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return Response.json({ error: 'use POST' }, { status: 405 });
  }

  const ip        = clientIpFrom(req);
  const userAgent = req.headers.get('user-agent') || '';

  let body: any;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: 'invalid_json' }, { status: 400 });
  }

  const ref = String(body?.ref ?? '').trim();
  if (!REF_REGEX.test(ref)) {
    return Response.json({ error: 'invalid_ref_format' }, { status: 400 });
  }

  // Rate-limit only valid-format requests so a flood of malformed refs from a
  // misbehaving client doesn't burn through the legitimate buyer's allowance.
  if (isRateLimited(ip)) {
    const base44 = createClientFromRequest(req);
    await logRateLimit(base44, ip, ref, userAgent);
    return Response.json({ error: 'rate_limited' }, { status: 429 });
  }

  const base44 = createClientFromRequest(req);

  let payment: any = null;
  try {
    const found = await base44.asServiceRole.entities.Payment.filter({
      gateway_reference: ref,
    });
    payment = unwrapOne(found);
  } catch (err) {
    console.error('[payment-public-summary] Payment lookup failed:', err);
    return Response.json({ error: 'lookup_failed' }, { status: 500 });
  }

  if (!payment?.id) {
    return Response.json({ error: 'not_found' }, { status: 404 });
  }

  // Client lookup is best-effort — we still return useful data even if the
  // Client row is missing for some reason.
  let client: any = null;
  if (payment.client_id) {
    try {
      const found = await base44.asServiceRole.entities.Client.filter({
        id: payment.client_id,
      });
      client = unwrapOne(found);
    } catch (err) {
      console.error('[payment-public-summary] Client lookup failed:', err);
    }
  }

  const packageId   = String(payment.package_id || '').trim();
  // Prefer the catalogue name (stable); fall back to PayFast's echoed
  // item_name (post-ITN) and finally the slug.
  const packageName =
    PACKAGE_NAMES[packageId] ||
    String(payment?.ipn_payload?.item_name || '').trim() ||
    packageId ||
    'your package';

  // Email source: Client.email is the only reliable source for cancelled /
  // pending payments (ipn_payload is empty until the ITN fires). After
  // success the ITN echoes the buyer's email which we use as a fallback if
  // the Client row is somehow missing.
  const email =
    String(client?.email || '').trim() ||
    String(payment?.ipn_payload?.email_address || '').trim() ||
    null;

  const customerName =
    String(client?.contact_person || '').trim() ||
    String(payment?.ipn_payload?.name_first || '').trim() ||
    null;

  const companyName =
    String(client?.business_name || '').trim() ||
    String(payment.client_name || '').trim() ||
    null;

  return Response.json({
    ref:            String(payment.gateway_reference || ref),
    pf_payment_id:  String(payment.gateway_pf_payment_id || '').trim() || null,
    package_id:     packageId,
    package_name:   packageName,
    amount:         Number(payment.amount || 0),
    status:         String(payment.status || 'pending'),
    customer_name:  customerName,
    company_name:   companyName,
    email,
    completed_at:   payment.completed_at || null,
    created_at:     payment.created_at || payment.createdAt || new Date(0).toISOString(),
  });
});
